# fly.toml app configuration file
app = 'pel-epo-automation'
primary_region = 'ord'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[deploy]
  release_command = 'npm run db:migrate'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/epo-automation'

[[vm]]
  size = 'shared-cpu-1x'

# Scheduled process for EPO automation
[processes]
  app = "npm start"
  cron = "node scripts/run-epo-automation.js"

[cron]
  "*/10 * * * *" = "node scripts/run-epo-automation.js"  # Every 10 minutes
